# Sheldon plugins configuration

shell = "zsh"
apply = ["source"]

[plugins.enhancd]
github = "b4b4r07/enhancd"
use = ["init.sh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"